version: 1
formatters:
  simple:
    format: '[%(asctime)s]  [%(process)d]  [%(levelname)s] [%(name)s]  %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: logs/application.log
    backupCount: 1
loggers:
  file_base_batch:
    level: DEBUG
    handlers: [file, console]
    propagate: no
root:
  level: INFO
  handlers: [file]


